"use client";

import Navbar from "@/Components/Navbar/Navbar";
import { ChakraProvider } from "@chakra-ui/react";
import { theme } from "../Chakra/Theme";

/*export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider theme={theme}>
          <Navbar />
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
